# Welcome to Jekyll!
#

# Site settings
title: Munch Research Group
description: |
  Population genomics of natural selection,<br>species formation and human neuro-development
owner: Kasper Munch # or company name
members:

  present:

    - name: Kasper Munch
      image: images/kasper_portrait.png
      description: PI. Population genomic analysis and modelling to understand the fundamental properties and mechanisms of selection, recombination, and speciation. 

    - name: Shannon D'Urso
      image: images/shannon.jpeg
      position: postdoc
      description: Shannon works on how intra-genomic conflicts in spermatogenesis shape the genetic basis of autism.

    - name: Johan Christensen Ulstrup
      image: images/placeholder.png
      description: As master student, Johan uses genomic pre-trained networks to compare sequence X chromosome sequence conservation across baboon species.

  former:

    - name: Søren Jørgensen
      image: images/placeholder.png
      description: As master student, Søren works on chromatin architecture spermatogenesis and its relation to selection on the X chromosome.

    - name: Erik Fogh Sørensen
      image: images/erik.png
      description: As PhD student, Erik works on how intragenomic conflicts shape X chromosome evolution and the development of hybrid incompatibilities between diverging populations.

    - name: Ariadna Saez Gomez
      image: images/ariadna_intern.jpeg
      description: As intern, Ariadna worked on identifying genomic elements responsible for strong selection on the X chromosome.

    - name: Davide Capozzi
      image: images/davide_intern.jpeg
      description: As intern, Davide worked on the dynamics of meiotic drive and on identifying signature patterns in genetic diversity for its identification.

    - name: Tobias Røikjer
      image: images/tobias.png
      description: As master student, Tobias worked on a graph-based formulation of phase-type distributions to compute the joint distribution of total branch length of lineages with different numbers of descendants and to compute the joint distribution of the site frequency spectrum in both a single population and in an isolation-with-migration model.

    - name: David Castellano
      image: images/david_castellano3.png
      description: As postdoc, David was funded by Independent Research Fund Denmark. He worked on distributions of fitness effects and the determinants of genetic variation across the genomes of great apes.

    - name: Jonas Berglund
      image: images/jonas_berglund2.png
      description: As postdoc, Jonas worked on GC-biased gene conversion and stability of hotspots in birds.


first_published: 2016 # if migrating another site, the year of your first publish
email: kaspermunch@birc.au.dk
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/<username>
  github: https://github.com/munch-group
  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
